"""add_avatar_field_to_users

Revision ID: 89457e2e19f9
Revises: 5b0ed860cc2b
Create Date: 2024-03-21 09:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89457e2e19f9'
down_revision: Union[str, None] = '5b0ed860cc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
        existing_type=sa.Text(),
        type_=sa.String(length=255),
        existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
        existing_type=sa.String(length=255),
        type_=sa.Text(),
        existing_nullable=True)
    # ### end Alembic commands ###
